const https=require('https');const http=require('http');
const IID='7107607381';const ITOKEN='06df99fcaf654e6dbd0d504cf1413b60144f1c48ac824ea2b5';
const GBASE='https://api.green-api.com';const OWNER='212716508833@c.us';
const KW=['مزروب','عاجل','urgent','مشكل','مفقود','رقم الموزع'];
const CITIES='مكناس:كل يوم|الخميسات:كل يوم|تيفلت:كل يوم|أزرو:الاثنين الأربعاء الجمعة|إفران:الاثنين الأربعاء الجمعة|بوفكران:الثلاثاء الخميس السبت|الحاجب:الثلاثاء الخميس السبت|سيدي قاسم:كل يوم|سيدي سليمان:كل يوم|سبعيون:كل يوم ما عدا الجمعة|أگوراي:الثلاثاء الجمعة|أيت يعزم:الثلاثاء الجمعة|مولاي إدريس:الأربعاء السبت|سبت جحجوح:الخميس|عين جيري:الخميس';
function req(url,opt,body){return new Promise((res,rej)=>{const u=new URL(url);const r=https.request({hostname:u.hostname,path:u.pathname+u.search,method:opt||'GET',headers:body?{'Content-Type':'application/json','Content-Length':Buffer.byteLength(body)}:{}},(x)=>{let d='';x.on('data',c=>d+=c);x.on('end',()=>{try{res(JSON.parse(d))}catch{res({})}})});r.on('error',()=>res({}));if(body)r.write(body);r.end();});}
async function ai(msg){const b=JSON.stringify({model:'llama3-8b-8192',messages:[{role:'system',content:`بوت Yanis Delivery. جدول التوصيل: ${CITIES}. رد بالدارجة أو الفرنسية. جملتين فقط مع إيموجي.`},{role:'user',content:msg}]});const r=await req('https://api.groq.com/openai/v1/chat/completions','POST',b);return r.choices?.[0]?.message?.content||null;}
async function send(id,msg){await req(`${GBASE}/waInstance${IID}/sendMessage/${ITOKEN}`,'POST',JSON.stringify({chatId:id,message:msg}));}
async function run(){try{const d=await req(`${GBASE}/waInstance${IID}/receiveNotification/${ITOKEN}`);if(!d?.receiptId)return;await req(`${GBASE}/waInstance${IID}/deleteNotification/${ITOKEN}/${d.receiptId}`,'DELETE');if(d.body?.typeWebhook!=='incomingMessageReceived')return;const txt=d.body.messageData?.textMessageData?.textMessage||'';const cid=d.body.senderData?.chatId||'';const name=d.body.senderData?.senderName||'عميل';if(!txt||!cid.includes('@g.us'))return;console.log(`[${name}]:${txt}`);if(KW.some(k=>txt.includes(k)))await send(OWNER,`🚨 ${name}: ${txt}`);const r=await ai(txt);if(r){await send(cid,r);console.log('رد:'+r);}}catch(e){console.error(e.message);}}
http.createServer((_,r)=>{r.writeHead(200);r.end('Yanis Bot OK');}).listen(process.env.PORT||3000,()=>{console.log('🚀 Bot running!');setInterval(run,5000);});
