const https=require('https');const http=require('http');
const IID='7107607381';const ITOKEN='06df99fcaf654e6dbd0d504cf1413b60144f1c48ac824ea2b5';
const GBASE='https://api.green-api.com';const OWNER='212716508833@c.us';
const GROQ='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';
const KW=['مزروب','عاجل','urgent','مشكل','مفقود','رقم الموزع'];
const CITIES='مكناس:كل يوم|الخميسات:كل يوم|تيفلت:كل يوم|أزرو:الاثنين الأربعاء الجمعة|إفران:الاثنين الأربعاء الجمعة|بوفكران:الثلاثاء الخميس السبت|الحاجب:الثلاثاء الخميس السبت|سيدي قاسم:كل يوم|سيدي سليمان:كل يوم|سبعيون:كل يوم ما عدا الجمعة|أگوراي:الثلاثاء الجمعة|أيت يعزم:الثلاثاء الجمعة|مولاي إدريس:الأربعاء السبت|سبت جحجوح:الخميس|عين جيري:الخميس';
function post(url,body,hdrs){return new Promise((res)=>{const u=new URL(url);const b=Buffer.from(body);const r=https.request({hostname:u.hostname,path:u.pathname,method:'POST',headers:{...hdrs,'Content-Length':b.length}},(x)=>{let d='';x.on('data',c=>d+=c);x.on('end',()=>{try{res(JSON.parse(d))}catch{res({})}})});r.on('error',()=>res({}));r.write(b);r.end();});}
async function ai(msg){const r=await post('https://api.groq.com/openai/v1/chat/completions',JSON.stringify({model:'llama3-8b-8192',messages:[{role:'system',content:`بوت Yanis Delivery. جدول التوصيل: ${CITIES}. رد بالدارجة أو الفرنسية. جملتين فقط مع إيموجي.`},{role:'user',content:msg}]}),{'Content-Type':'application/json','Authorization':`Bearer ${GROQ}`});return r.choices?.[0]?.message?.content||null;}
async function send(id,msg){await post(`${GBASE}/waInstance${IID}/sendMessage/${ITOKEN}`,JSON.stringify({chatId:id,message:msg}),{'Content-Type':'application/json'});}
http.createServer(async(req,res)=>{if(req.method==='POST'&&req.url==='/webhook'){let body='';req.on('data',c=>body+=c);req.on('end',async()=>{try{const d=JSON.parse(body);const txt=d.messageData?.textMessageData?.textMessage||'';const cid=d.senderData?.chatId||'';const name=d.senderData?.senderName||'عميل';console.log(`[${name}]:${txt}`);if(txt&&cid.includes('@g.us')){if(KW.some(k=>txt.includes(k)))await send(OWNER,`🚨 ${name}: ${txt}`);const r=await ai(txt);if(r)await send(cid,r);}res.writeHead(200);res.end('OK');}catch(e){console.error(e.message);res.writeHead(200);res.end('OK');}});}else{res.writeHead(200);res.end('Yanis Bot OK');}}).listen(process.env.PORT||3000,()=>console.log('🚀 Webhook Bot running!'));
